// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)
