databases:
  - name: postgres
    ipAllowList: []
    databaseName: talii
    user: talii

services:
  - type: web
    name: talii
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false