Rails.application.routes.draw do
  root to: "pets#current_pet_profile"

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/health", to: proc { [200, { "Content-Type" => "text/plain" }, ["ok"]] }

  # MOBILE APP ROUTES
  patch "/mobile_app/update/:id", to: "users#update", as: "update_user"
  delete "/mobile_app/delete/:id", to: "users#delete", as: "delete_user"
  get "/mobile_app/reset_password", to: "users#reset_password", as: "reset_password"
  post "/mobile_app/update_password", to: "users#update_password", as: "update_password"

  get "/mobile_app/login", to: "sessions#new", as: "new_session"
  post "/mobile_app/login", to: "sessions#create", as: "create_session"

  get "/mobile_app/logout", to: "sessions#destroy", as: "destroy_session"
  post "/mobile_app/set_current_pet/:id", to: "sessions#set_current_pet", as: "set_current_pet"

  get "/mobile_app/pets/current_pet_profile", to: "pets#current_pet_profile", as: "current_pet_profile"
  get "/mobile_app/pets/:id", to: "pets#show", as: "pet"
  get "/mobile_app/pets/:id/pictures", to: "pets#pictures", as: "pet_pictures"
  post "/mobile_app/create/pets/:id/images", to: "pets#upload_new_image", as: "upload_new_image"
  patch "/mobile_app/update/pets/:id", to: "pets#update", as: "update_pet"
  delete "/mobile_app/pets/:id", to: "pets#delete", as: "delete_pet"
  delete "/mobile_app/pets/:id/images/:image_id", to: "pets#delete_image", as: "delete_image"

  get "/mobile_app/grooms", to: "grooms#index", as: "grooms"
  get "/mobile_app/grooms/:id", to: "grooms#show", as: "groom"
  get "/mobile_app/create/grooms", to: "grooms#new", as: "new_groom"
  post "/mobile_app/create/grooms", to: "grooms#create", as: "create_groom"
  patch "/mobile_app/update/grooms/:id", to: "grooms#update", as: "update_groom"
  patch "/mobile_app/confirm/grooms/:id", to: "grooms#confirm", as: "confirm_groom"
  delete "/mobile_app/grooms/:id", to: "grooms#delete", as: "delete_groom"
  
  get "/mobile_app/daycare_visits", to: "daycare_visits#index", as: "daycare_visits"
  get "/mobile_app/daycare_visits/:id", to: "daycare_visits#show", as: "daycare_visit"
  get "/mobile_app/create/daycare_visits", to: "daycare_visits#new", as: "new_daycare_visits"
  post "/mobile_app/create/daycare_visits", to: "daycare_visits#create", as: "create_daycare_visits"
  patch "/mobile_app/update/daycare_visits/:id", to: "daycare_visits#update", as: "update_daycare_visits"
  patch "/mobile_app/confirm/daycare_visits/:id", to: "daycare_visits#confirm", as: "confirm_daycare_visits"
  delete "/mobile_app/daycare_visits/:id", to: "daycare_visits#delete", as: "delete_daycare_visits"

  get "/mobile_app/shop", to: "shop#shop", as: "shop"
  get "/mobile_app/shop/categories/:id", to: "shop#category", as: "category"
  get "/mobile_app/shop/products/:id", to: "shop#product", as: "product"
  get "/mobile_app/shop/products/:id/review", to: "shop#review", as: "new_review"
  post "/mobile_app/shop/products/:id/review", to: "shop#create_review", as: "create_review"
  post "/mobile_app/shop/products/:id/add_to_cart", to: "shop#add_to_cart", as: "add_to_cart"
  get "/mobile_app/shop/cart", to: "shop#cart", as: "cart"

  get "/mobile_app/orders", to: "orders#index", as: "orders"
  post "/mobile_app/orders", to: "orders#create", as: "create_order"
  get "/mobile_app/orders/:id/pay", to: "payments#pay", as: "pay"
  post "/mobile_app/webhooks/payment", to: "payments#webhook"

  get "/mobile_app/settings", to: "settings#index", as: "settings"

  get "/mobile_app/settings/pet_profiles", to: "settings#pet_profiles", as: "pet_profiles"
  get "/mobile_app/settings/pet_profiles/:id", to: "settings#pet_profile", as: "pet_profile"

  get "/mobile_app/settings/pet_selection", to: "settings#pet_selection", as: "pet_selection"
  post "/mobile_app/settings/pet_selection", to: "settings#switch_pet", as: "switch_pet"

  get "/mobile_app/settings/user_profile", to: "settings#user_profile", as: "user_profile"
  post "/mobile_app/settings/user_profile/edit", to: "settings#update_user_profile", as: "update_user_profile"

  get "/mobile_app/onboarding/pets", to: "pets/onboarding#new", as: "new_pet_onboarding"
  get "/mobile_app/onboarding/pets/:id/species", to: "pets/onboarding#species", as: "pet_species_onboarding"
  post "/mobile_app/onboarding/pets/:id/species", to: "pets/onboarding#update_species", as: "update_pet_species_onboarding"
  get "/mobile_app/onboarding/pets/:id/name", to: "pets/onboarding#name", as: "pet_name_onboarding"
  post "/mobile_app/onboarding/pets/:id/name", to: "pets/onboarding#update_name", as: "update_pet_name_onboarding"
  get "/mobile_app/onboarding/pets/:id/gender", to: "pets/onboarding#gender", as: "pet_gender_onboarding"
  post "/mobile_app/onboarding/pets/:id/gender", to: "pets/onboarding#update_gender", as: "update_pet_gender_onboarding"
  get "/mobile_app/onboarding/pets/:id/dob", to: "pets/onboarding#dob", as: "pet_dob_onboarding"
  post "/mobile_app/onboarding/pets/:id/dob", to: "pets/onboarding#update_dob", as: "update_pet_dob_onboarding"
  get "/mobile_app/onboarding/pets/:id/weight", to: "pets/onboarding#weight", as: "pet_weight_onboarding"
  post "/mobile_app/onboarding/pets/:id/weight", to: "pets/onboarding#update_weight", as: "update_pet_weight_onboarding"
  get "/mobile_app/onboarding/pets/:id/breed", to: "pets/onboarding#breed", as: "pet_breed_onboarding"
  post "/mobile_app/onboarding/pets/:id/breed", to: "pets/onboarding#update_breed", as: "update_pet_breed_onboarding"
  get "/mobile_app/onboarding/pets/:id/health_conditions", to: "pets/onboarding#health_conditions", as: "pet_health_conditions_onboarding"
  post "/mobile_app/onboarding/pets/:id/health_conditions", to: "pets/onboarding#update_health_conditions", as: "update_pet_health_conditions_onboarding"
  get "/mobile_app/onboarding/pets/:id/images", to: "pets/onboarding#images", as: "pet_images_onboarding"
  post "/mobile_app/onboarding/pets/:id/images", to: "pets/onboarding#upload_image", as: "upload_pet_image_onboarding"

  get "/mobile_app/sign_up", to: "onboarding_users#new", as: "new_user_onboarding"
  get "/mobile_app/onboarding/user/:id/access_code", to: "onboarding_users#access_code", as: "user_access_code_onboarding"
  post "/mobile_app/onboarding/user/:id/access_code", to: "onboarding_users#update_access_code", as: "update_user_access_code_onboarding"
  get "/mobile_app/onboarding/user/:id/email", to: "onboarding_users#email", as: "user_email_onboarding"
  post "/mobile_app/onboarding/user/:id/email", to: "onboarding_users#update_email", as: "update_user_email_onboarding"
  get "/mobile_app/onboarding/user/:id/password", to: "onboarding_users#password", as: "user_password_onboarding"
  post "/mobile_app/onboarding/user/:id/password", to: "onboarding_users#update_password", as: "update_user_password_onboarding"
  get "/mobile_app/onboarding/user/:id/name", to: "onboarding_users#name", as: "user_name_onboarding"
  post "/mobile_app/onboarding/user/:id/name", to: "onboarding_users#update_name", as: "update_user_name_onboarding"
  get "/mobile_app/onboarding/user/:id/phone", to: "onboarding_users#phone", as: "user_phone_onboarding"
  post "/mobile_app/onboarding/user/:id/phone", to: "onboarding_users#update_phone", as: "update_user_phone_onboarding"
  get "/mobile_app/onboarding/user/:id/address", to: "onboarding_users#address", as: "user_address_onboarding"
  post "/mobile_app/onboarding/user/:id/address", to: "onboarding_users#update_address", as: "update_user_address_onboarding"
  get "/mobile_app/onboarding/user/:id/complete", to: "onboarding_users#complete", as: "complete_user_onboarding"
  post "/mobile_app/onboarding/user/:id/create", to: "onboarding_users#create_user", as: "create_user_onboarding"

  # DESKTOP APP ROUTES
  get "/dashboard", to: "desktop/dashboard#index", as: "desktop_dashboard"

  get "/grooms", to: "desktop/grooms#index", as: "desktop_grooms"
  get "/grooms/new", to: "desktop/grooms#new", as: "desktop_grooms_new"
  get "/grooms/:id", to: "desktop/grooms#show", as: "desktop_groom"
  get "/grooms/:id/images", to: "desktop/grooms#images", as: "desktop_groom_images"
  post "/grooms/:id/images/upload", to: "desktop/grooms#upload_image", as: "desktop_groom_images_upload"
  delete "/grooms/:id/images/:image_id", to: "desktop/grooms#destroy_image", as: "desktop_groom_images_destroy"
  patch "/grooms/:id/update", to: "desktop/grooms#update", as: "desktop_groom_update"
  post "/bookings/:id/log_report/create", to: "desktop/log_reports#create", as: "desktop_groom_log_report_create"
  patch "/bookings/:id/log_report/update", to: "desktop/log_reports#update", as: "desktop_groom_log_report_update"
  
  get "/temporary_grooms/new", to: "desktop/temporary_grooms#new", as: "desktop_temporary_grooms_new"
  get "/temporary_grooms/:id", to: "desktop/temporary_grooms#show", as: "desktop_temporary_groom"
  post "/temporary_grooms/create", to: "desktop/temporary_grooms#create", as: "desktop_temporary_grooms_create"
  get "/temporary_grooms/:id/images", to: "desktop/temporary_grooms#images", as: "desktop_temporary_groom_images"
  post "/temporary_grooms/:id/images/upload", to: "desktop/temporary_grooms#upload_image", as: "desktop_temporary_groom_images_upload"
  delete "/temporary_grooms/:id/images/:image_id", to: "desktop/temporary_grooms#destroy_image", as: "desktop_temporary_groom_images_destroy"
  patch "/temporary_grooms/:id/update", to: "desktop/temporary_grooms#update", as: "desktop_temporary_groom_update"
  
  get "/daycare_visits", to: "desktop/daycare_visits#index", as: "desktop_daycare_visits"
  get "/daycare_visits/new", to: "desktop/daycare_visits#new", as: "desktop_daycare_visits_new"
  get "/daycare_visits/:id", to: "desktop/daycare_visits#show", as: "desktop_daycare_visit"
  patch "/daycare_visits/:id/update", to: "desktop/daycare_visits#update", as: "desktop_daycare_visit_update"

  get "/temporary_daycare_visits/new", to: "desktop/temporary_daycare_visits#new", as: "desktop_temporary_daycare_visits_new"
  get "/temporary_daycare_visits/:id", to: "desktop/temporary_daycare_visits#show", as: "desktop_temporary_daycare_visit"
  post "/temporary_daycare_visits/create", to: "desktop/temporary_daycare_visits#create", as: "desktop_temporary_daycare_visit_create"
  patch "/temporary_daycare_visits/:id/update", to: "desktop/temporary_daycare_visits#update", as: "desktop_temporary_daycare_visit_update"

  # customer routes
  get "/users", to: "desktop/users/customers#index", as: "desktop_users"
  get "/users/new", to: "desktop/users/customers#new", as: "desktop_users_new"
  get "/users/:id", to: "desktop/users/customers#show", as: "desktop_user"
  get "/users/:id/edit", to: "desktop/users/customers#edit", as: "desktop_user_edit"
  get "/users/:id/booking_settings/edit", to: "desktop/users/customers#booking_settings", as: "desktop_user_booking_settings_edit"

  # employee routes
  get "/employees", to: "desktop/users/employees#index", as: "desktop_employees"
  get "/employees/new", to: "desktop/users/employees#new", as: "desktop_employees_new"
  post "/employees/create", to: "desktop/users/users#create_staff", as: "desktop_create_staff"
  get "/employees/:id", to: "desktop/users/employees#show", as: "desktop_employee"
  get "/employees/:id/edit", to: "desktop/users/employees#edit", as: "desktop_employee_edit"
  
  # generic user action routes
  get "/users/new", to: "desktop/users/users#new", as: "desktop_user_new"
  post "/users/create", to: "desktop/users/users#create", as: "desktop_users_create"
  post "/customers/create", to: "desktop/users/users#create_customer", as: "desktop_customers_create"
  patch "/users/:id/update", to: "desktop/users/users#update", as: "desktop_user_update"
  delete "/users/:id/delete", to: "desktop/users/users#delete", as: "desktop_user_delete"

  get "/products", to: "desktop/products#index", as: "desktop_products"
  get "/products/new", to: "desktop/products#new", as: "desktop_products_new"
  post "/products/create", to: "desktop/products#create", as: "desktop_products_create"
  get "/products/:id", to: "desktop/products#show", as: "desktop_product"
  get "/products/:id/edit", to: "desktop/products#edit", as: "desktop_product_edit"
  patch "/products/:id/update", to: "desktop/products#update", as: "desktop_products_update"
  delete "/products/:id/delete", to: "desktop/products#delete", as: "desktop_products_delete"

  get "/products/:id/pictures", to: "desktop/products#pictures", as: "desktop_product_pictures"
  post "/products/:id/pictures/create", to: "desktop/products#upload_new_image", as: "desktop_product_pictures_upload"
  delete "/products/:id/images/:image_id", to: "desktop/products#delete_product_picture", as: "desktop_product_pictures_delete"

  get "/categories", to: "desktop/categories#index", as: "desktop_categories"
  get "/categories/new", to: "desktop/categories#new", as: "desktop_categories_new"
  post "/categories/create", to: "desktop/categories#create", as: "desktop_categories_create"
  get "/categories/:id", to: "desktop/categories#show", as: "desktop_category"
  get "/categories/:id/edit", to: "desktop/categories#edit", as: "desktop_category_edit"
  patch "/categories/:id/update", to: "desktop/categories#update", as: "desktop_categories_update"
  delete "/categories/:id/delete", to: "desktop/categories#delete", as: "desktop_categories_delete"

  get "/categories/:id/pictures", to: "desktop/categories#pictures", as: "desktop_category_pictures"
  post "/categories/:id/pictures/create", to: "desktop/categories#upload_new_image", as: "desktop_category_pictures_upload"
  delete "/categories/:id/images/:image_id", to: "desktop/categories#delete_category_picture", as: "desktop_category_pictures_delete"

  get "/users/:id/pets/new", to: "desktop/pets#new", as: "desktop_pets_new"
  post "/pets/create", to: "desktop/pets#create", as: "desktop_pets_create"
  patch "/pets/:id", to: "desktop/pets#update", as: "desktop_pets_update"
  get "/pets/:id", to: "desktop/pets#show", as: "desktop_pets"
  get "/pets/:id/images", to: "desktop/pets#pictures", as: "desktop_pets_pictures"
  get "/pets/:id/rabies_evidence", to: "desktop/pets#download_rabies_evidence", as: "desktop_pets_download_rabies_evidence"
  get "/pets/:id/bordetella_evidence", to: "desktop/pets#download_bordetella_evidence", as: "desktop_pets_download_bordetella_evidence"
  get "/pets/:id/dhpp_evidence", to: "desktop/pets#download_dhpp_evidence", as: "desktop_pets_download_dhpp_evidence"
  get "/pets/:id/heartworm_evidence", to: "desktop/pets#download_heartworm_evidence", as: "desktop_pets_download_heartworm_evidence"
  get "/pets/:id/kennel_cough_evidence", to: "desktop/pets#download_kennel_cough_evidence", as: "desktop_pets_download_kennel_cough_evidence"
  post "/pets/:id/images", to: "desktop/pets#upload_new_image", as: "desktop_pets_pictures_upload"
  delete "/pets/:id/images/:image_id", to: "desktop/pets#delete_pet_picture", as: "desktop_pets_pictures_delete"
  delete "/pets/:id", to: "desktop/pets#delete", as: "desktop_pets_delete"

  get "/reports", to: "desktop/reports#index", as: "desktop_reports"

  get "/settings", to: "desktop/settings#index", as: "desktop_settings"
  get "/settings/user", to: "desktop/settings#user", as: "desktop_user_settings"
  patch "/settings/user", to: "desktop/settings#update_user", as: "update_desktop_user_settings"
  patch "/settings/update_profile_picture", to: "desktop/settings#update_profile_picture", as: "update_desktop_profile_picture_settings"
  patch "/settings/update_password", to: "desktop/settings#update_password", as: "update_desktop_password"
  get "/settings/organisation", to: "desktop/settings#organisation", as: "desktop_organisation_settings"
  patch "/settings/organisation", to: "desktop/settings#update_organisation", as: "update_desktop_organisation_settings"
  get "/settings/staff", to: "desktop/settings#staff", as: "desktop_staff_settings"
  get "/settings/retail", to: "desktop/settings#retail", as: "desktop_retail_settings"
  patch "/settings/retail", to: "desktop/settings#update_retail", as: "update_desktop_retail_settings"

  get "/organisations/new", to: "desktop/organisations#new", as: "desktop_organisations_new"
  post "/organisations/create", to: "desktop/organisations#create", as: "desktop_organisations_create"

  get "/imports", to: "desktop/imports#import", as: "desktop_import"
  get "/example_customer_csv", to: "desktop/imports#example_customer_csv", as: "example_customer_csv"
  get "/example_staff_csv", to: "desktop/imports#example_staff_csv", as: "example_staff_csv"
  get "/example_pets_csv", to: "desktop/imports#example_pets_csv", as: "example_pets_csv"
  post "/imports/customers", to: "desktop/imports#import_customers", as: "desktop_import_customers"
  post "/imports/staff", to: "desktop/imports#import_staff", as: "desktop_import_staff"
  post "/imports/pets", to: "desktop/imports#import_pets", as: "desktop_import_pets"

  get "/sign_up", to: "desktop/onboarding_organisations#user_details", as: "desktop_onboarding_organisation_user_details"
  post "/onboarding/organisation/user_details", to: "desktop/onboarding_organisations#update_user_details", as: "update_desktop_onboarding_organisation_user_details"
  get "/onboarding/organisation/:id/organisation_details", to: "desktop/onboarding_organisations#organisation_details", as: "desktop_onboarding_organisation_organisation_details"
  post "/onboarding/organisation/:id/complete", to: "desktop/onboarding_organisations#create_organisation", as: "update_desktop_onboarding_organisation_complete"

  get "/login", to: "desktop/sessions#new", as: "desktop_new_session"
  post "/login", to: "desktop/sessions#create", as: "desktop_create_session"
  get "/logout", to: "desktop/sessions#destroy", as: "desktop_destroy_session"

  # Employee App Routes
  get "/employee_app/dashboard", to: "employee_app/mobile_app#profile", as: "mobile_app_profile"

  get "/employee_app/settings", to: "employee_app/mobile_app#user_settings", as: "employee_app_settings"
  patch "/employee_app/settings", to: "employee_app/mobile_app#update_user_settings", as: "employee_app_update_user_settings"

  get "/employee_app/grooms", to: "employee_app/grooms#index", as: "employee_app_grooms"
  get "/employee_app/grooms/:id", to: "employee_app/grooms#show", as: "employee_app_groom"
  patch "/employee_app/grooms/:id/update", to: "employee_app/grooms#update", as: "employee_app_groom_update"
  get "/employee_app/grooms/:id/images", to: "employee_app/grooms#images", as: "employee_app_groom_images"
  post "/employee_app/grooms/:id/images/upload", to: "employee_app/grooms#upload_image", as: "employee_app_groom_images_upload"
  delete "/employee_app/grooms/:id/images/:image_id", to: "employee_app/grooms#destroy_image", as: "employee_app_groom_images_destroy"

  get "/employee_app/temporary_grooms/:id", to: "employee_app/temporary_grooms#show", as: "employee_app_temporary_groom"
  patch "/employee_app/temporary_grooms/:id/update", to: "employee_app/temporary_grooms#update", as: "employee_app_temporary_groom_update"
  get "/employee_app/temporary_grooms/:id/images", to: "employee_app/temporary_grooms#images", as: "employee_app_temporary_groom_images"
  post "/employee_app/temporary_grooms/:id/images/upload", to: "employee_app/temporary_grooms#upload_image", as: "employee_app_temporary_groom_images_upload"
  delete "/employee_app/temporary_grooms/:id/images/:image_id", to: "employee_app/temporary_grooms#destroy_image", as: "employee_app_temporary_groom_images_destroy"

  get "/employee_app/daycare_visits", to: "employee_app/daycare_visits#index", as: "employee_app_daycare_visits"
  get "/employee_app/daycare_visits/:id", to: "employee_app/daycare_visits#show", as: "employee_app_daycare_visit"
  patch "/employee_app/daycare_visits/:id/update", to: "employee_app/daycare_visits#update", as: "employee_app_daycare_visit_update"

  get "/employee_app/temporary_daycare_visits/:id", to: "employee_app/temporary_daycare_visits#show", as: "employee_app_temporary_daycare_visit"
  patch "/employee_app/temporary_daycare_visits/:id/update", to: "employee_app/temporary_daycare_visits#update", as: "employee_app_temporary_daycare_visit_update"
end
